project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    - courses.qmd
    - resume.qmd
    - energy_project.qmd
    - gis_project.qmd
    - soil_project.qmd
    - wildfire_project.qmd
    - projects.qmd
    - Project_ENVS193DS_homework3.qmd

website:
  title: "Adrianna Martinez"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Courses"
        href: courses.qmd
      - text: "Resume"
        href: resume.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

