project:
  type: website
  output-dir: docs

website:
  title: "mysite"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Courses"
        href: courses.qmd
      - text: "Resume"
        href: resume.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

